import type { Proposal, Client } from '@/types/database'

const SECTION_TITLES: Record<string, string> = {
  executive_summary: 'Executive Summary',
  current_state: 'Current State Assessment',
  opportunities: 'Prioritized Opportunities',
  pilot: 'Recommended Pilot',
  timeline: 'Timeline & Next Steps',
  risks: 'Risks & Assumptions',
  technical: 'Technical Architecture',
  pricing: 'Pricing Breakdown',
  case_studies: 'Evidence & Case Studies',
}

export function generateMarkdown(
  proposal: Proposal,
  client: Client
): string {
  const lines: string[] = []

  // Header
  lines.push(`# ${proposal.title}`)
  lines.push('')
  lines.push(`**Client:** ${client.company_name}`)
  lines.push(`**Contact:** ${client.contact_name} (${client.email})`)
  lines.push(`**Date:** ${new Date(proposal.created_at).toLocaleDateString()}`)
  lines.push('')
  lines.push('---')
  lines.push('')

  // Sections
  const content = proposal.content as Record<string, string>

  for (const sectionId of proposal.enabled_sections) {
    const sectionContent = content[sectionId]
    if (sectionContent) {
      lines.push(`## ${SECTION_TITLES[sectionId] || sectionId}`)
      lines.push('')
      // Strip HTML tags for plain markdown
      lines.push(stripHtml(sectionContent))
      lines.push('')
    }
  }

  // Footer
  lines.push('---')
  lines.push('')
  lines.push('*Generated by Inerci AI - AI Automation Agency*')
  lines.push(`*[www.inerci.ai](https://inerci.ai)*`)

  return lines.join('\n')
}

function stripHtml(html: string): string {
  return html
    // Convert headers
    .replace(/<h1[^>]*>(.*?)<\/h1>/gi, '# $1\n')
    .replace(/<h2[^>]*>(.*?)<\/h2>/gi, '## $1\n')
    .replace(/<h3[^>]*>(.*?)<\/h3>/gi, '### $1\n')
    // Convert lists
    .replace(/<ul[^>]*>/gi, '')
    .replace(/<\/ul>/gi, '')
    .replace(/<ol[^>]*>/gi, '')
    .replace(/<\/ol>/gi, '')
    .replace(/<li[^>]*>(.*?)<\/li>/gi, '- $1\n')
    // Convert emphasis
    .replace(/<strong[^>]*>(.*?)<\/strong>/gi, '**$1**')
    .replace(/<b[^>]*>(.*?)<\/b>/gi, '**$1**')
    .replace(/<em[^>]*>(.*?)<\/em>/gi, '*$1*')
    .replace(/<i[^>]*>(.*?)<\/i>/gi, '*$1*')
    // Convert paragraphs
    .replace(/<p[^>]*>(.*?)<\/p>/gi, '$1\n\n')
    // Convert line breaks
    .replace(/<br\s*\/?>/gi, '\n')
    // Remove remaining tags
    .replace(/<[^>]+>/g, '')
    // Clean up whitespace
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}
