import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

// Note: For production PDF generation, you'd use @react-pdf/renderer
// This is a simplified version that returns HTML for printing
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { proposalId } = await request.json()

    if (!proposalId) {
      return NextResponse.json({ error: 'Missing proposal ID' }, { status: 400 })
    }

    const { data: proposalData, error } = await supabase
      .from('proposals')
      .select('*, client:clients(*)')
      .eq('id', proposalId)
      .single()

    if (error || !proposalData) {
      return NextResponse.json({ error: 'Proposal not found' }, { status: 404 })
    }

    const proposal = proposalData as unknown as {
      title: string
      created_at: string
      enabled_sections: string[]
      content: Record<string, string>
      client: { company_name: string; contact_name: string; email: string }
    }

    const client = proposal.client
    const content = proposal.content

    const SECTION_TITLES: Record<string, string> = {
      executive_summary: 'Executive Summary',
      current_state: 'Current State Assessment',
      opportunities: 'Prioritized Opportunities',
      pilot: 'Recommended Pilot',
      timeline: 'Timeline & Next Steps',
      risks: 'Risks & Assumptions',
      technical: 'Technical Architecture',
      pricing: 'Pricing Breakdown',
      case_studies: 'Evidence & Case Studies',
    }

    // Generate printable HTML
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${proposal.title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Inter', sans-serif;
      line-height: 1.6;
      color: #1a1a2e;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
    }

    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 2px solid #3b82f6;
    }

    .logo {
      font-size: 24px;
      font-weight: 700;
      color: #3b82f6;
      margin-bottom: 20px;
    }

    h1 {
      font-size: 28px;
      font-weight: 700;
      margin-bottom: 10px;
    }

    .meta {
      color: #6b7280;
      font-size: 14px;
    }

    h2 {
      font-size: 20px;
      font-weight: 600;
      margin-top: 30px;
      margin-bottom: 15px;
      color: #1a1a2e;
      padding-bottom: 8px;
      border-bottom: 1px solid #e5e7eb;
    }

    .section {
      margin-bottom: 25px;
    }

    .content {
      font-size: 14px;
      color: #374151;
    }

    .content p {
      margin-bottom: 10px;
    }

    .content ul, .content ol {
      margin-left: 20px;
      margin-bottom: 10px;
    }

    .content li {
      margin-bottom: 5px;
    }

    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      font-size: 12px;
      color: #6b7280;
    }

    @media print {
      body {
        padding: 20px;
      }

      .section {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">INERCI</div>
    <h1>${proposal.title}</h1>
    <div class="meta">
      <p><strong>Prepared for:</strong> ${client.company_name}</p>
      <p><strong>Contact:</strong> ${client.contact_name} (${client.email})</p>
      <p><strong>Date:</strong> ${new Date(proposal.created_at).toLocaleDateString()}</p>
    </div>
  </div>

  ${proposal.enabled_sections
    .map((sectionId: string) => {
      const sectionContent = content[sectionId]
      if (!sectionContent) return ''
      return `
      <div class="section">
        <h2>${SECTION_TITLES[sectionId] || sectionId}</h2>
        <div class="content">${sectionContent}</div>
      </div>
      `
    })
    .join('')}

  <div class="footer">
    <p>Generated by Inerci AI - AI Automation Agency</p>
    <p>www.inerci.ai</p>
  </div>
</body>
</html>
`

    return new Response(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="${proposal.title}.html"`,
      },
    })
  } catch (error) {
    console.error('PDF export error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
